Repository dnd-side-project/dnd-11th-4-backend, pull requests merged in 2024-09, with the labels that each got.

#26 [#23] 내 방문기록 조회 API 추가
  build.gradle
  src/main/java/com/dnd/dndtravel/config/JpaConfig.java
  src/main/java/com/dnd/dndtravel/map/controller/MapController.java
  src/main/java/com/dnd/dndtravel/map/domain/MemberAttraction.java
  src/main/java/com/dnd/dndtravel/map/repository/MemberAttractionRepository.java
  src/main/java/com/dnd/dndtravel/map/repository/PhotoRepository.java
  src/main/java/com/dnd/dndtravel/map/repository/custom/MemberAttractionRepositoryCustom.java
  src/main/java/com/dnd/dndtravel/map/repository/custom/MemberAttractionRepositoryImpl.java
  src/main/java/com/dnd/dndtravel/map/repository/custom/PhotoRepositoryCustom.java
  src/main/java/com/dnd/dndtravel/map/repository/custom/PhotoRepositoryImpl.java
  src/main/java/com/dnd/dndtravel/map/repository/dto/projection/AttractionPhotoProjection.java
  src/main/java/com/dnd/dndtravel/map/repository/dto/projection/RecordProjection.java
  src/main/java/com/dnd/dndtravel/map/service/MapService.java
  src/main/java/com/dnd/dndtravel/map/service/dto/response/AttractionRecordResponse.java
  src/main/resources/application.yml
  src/test/java/com/dnd/dndtravel/map/service/MapServiceTest.java
Labels: enhancement

#30 [#29] refresh token 재발급 API 추가
  src/main/java/com/dnd/dndtravel/auth/controller/AuthController.java
  src/main/java/com/dnd/dndtravel/auth/controller/request/ReIssueTokenRequest.java
  src/main/java/com/dnd/dndtravel/auth/repository/RefreshTokenRepository.java
  src/main/java/com/dnd/dndtravel/auth/service/JwtProvider.java
  src/main/java/com/dnd/dndtravel/auth/service/JwtTokenService.java
  src/main/java/com/dnd/dndtravel/auth/service/dto/response/ReissueTokenResponse.java
Labels: enhancement

#28 [#27] 방문기록 상세보기, 수정, 삭제
  src/main/java/com/dnd/dndtravel/map/controller/MapController.java
  src/main/java/com/dnd/dndtravel/map/controller/request/UpdateRecordRequest.java
  src/main/java/com/dnd/dndtravel/map/domain/Attraction.java
  src/main/java/com/dnd/dndtravel/map/domain/MemberAttraction.java
  src/main/java/com/dnd/dndtravel/map/repository/AttractionRepository.java
  src/main/java/com/dnd/dndtravel/map/repository/MemberAttractionRepository.java
  src/main/java/com/dnd/dndtravel/map/repository/custom/MemberAttractionRepositoryCustom.java
  src/main/java/com/dnd/dndtravel/map/repository/custom/MemberAttractionRepositoryImpl.java
  src/main/java/com/dnd/dndtravel/map/service/MapService.java
  src/main/java/com/dnd/dndtravel/map/service/PhotoService.java
  src/main/java/com/dnd/dndtravel/map/service/dto/response/AttractionRecordDetailViewResponse.java
Labels: enhancement

#38 [#36] 마이페이지, 랜덤 닉네임 생성 기능 추가
  src/main/java/com/dnd/dndtravel/auth/controller/AuthController.java
  src/main/java/com/dnd/dndtravel/auth/service/MemberNameGenerator.java
  src/main/java/com/dnd/dndtravel/common/CommonExceptionHandler.java
  src/main/java/com/dnd/dndtravel/member/controller/MemberController.java
  src/main/java/com/dnd/dndtravel/member/service/MemberService.java
  src/main/java/com/dnd/dndtravel/member/service/response/MyPageResponse.java
  src/main/resources/application.yml
Labels: enhancement

#40 헤더 토큰 파싱 버그 수정
  src/main/java/com/dnd/dndtravel/auth/service/JwtProvider.java
  src/main/java/com/dnd/dndtravel/config/AuthResolver.java
Labels: bug

#37 #32 회원 탈퇴 api
  src/main/generated/com/dnd/dndtravel/auth/domain/QRefreshToken.java
  src/main/generated/com/dnd/dndtravel/map/domain/QAttraction.java
  src/main/generated/com/dnd/dndtravel/map/domain/QMemberAttraction.java
  src/main/generated/com/dnd/dndtravel/map/domain/QMemberRegion.java
  src/main/generated/com/dnd/dndtravel/map/domain/QPhoto.java
  src/main/generated/com/dnd/dndtravel/map/domain/QRegion.java
  src/main/generated/com/dnd/dndtravel/member/domain/QMember.java
  src/main/java/com/dnd/dndtravel/auth/controller/AuthController.java
  src/main/java/com/dnd/dndtravel/auth/controller/request/AppleWithdrawRequest.java
  src/main/java/com/dnd/dndtravel/auth/service/AppleClient.java
  src/main/java/com/dnd/dndtravel/auth/service/AppleOAuthService.java
  src/main/java/com/dnd/dndtravel/auth/service/dto/response/AppleRevokeResponse.java
  src/main/java/com/dnd/dndtravel/member/service/MemberService.java
Labels: enhancement

#43 #42 회원 탈퇴 커스텀 예외 처리
  src/main/java/com/dnd/dndtravel/auth/exception/AppleTokenRevokeException.java
  src/main/java/com/dnd/dndtravel/auth/service/AppleOAuthService.java
  src/main/java/com/dnd/dndtravel/common/CommonExceptionHandler.java
Labels: enhancement

#44 #41 Swagger Update
  src/main/java/com/dnd/dndtravel/auth/controller/request/AppleWithdrawRequest.java
  src/main/java/com/dnd/dndtravel/auth/controller/swagger/AuthControllerSwagger.java
  src/main/java/com/dnd/dndtravel/config/SwaggerConfig.java
Labels: documentation

#46 #45 Server URL 설정
  src/main/java/com/dnd/dndtravel/config/SwaggerConfig.java
Labels: bug

#54 #52 운영 서버 모니터링 구축
  build.gradle
  src/main/resources/application.yml
  src/main/resources/logback.xml
Labels: enhancement
